2024-10-29 01:08:00 - INFO - __main__ - Initializing training script
2024-10-29 01:08:00 - INFO - __main__ - Loading dataset...
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    train_dataset, eval_dataset = get_dataset(model_args.dataset, sep_token="[SEP]")
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 149, in get_dataset
    train_dataset, test_dataset = get_single_dataset(dataset_name, sep_token)
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 114, in get_single_dataset
    train_dataset, test_dataset = get_restaurant_dataset(first_name, second_name, sep_token)
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 62, in get_restaurant_dataset
    with open(train_dir, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SemEval14-res/train.json'
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    train_dataset, eval_dataset = get_dataset(model_args.dataset, sep_token="[SEP]")
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 149, in get_dataset
    train_dataset, test_dataset = get_single_dataset(dataset_name, sep_token)
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 114, in get_single_dataset
    train_dataset, test_dataset = get_restaurant_dataset(first_name, second_name, sep_token)
  File "C:\Users\18519\Desktop\2024F NLP-DL\HWs\HW2\task2\task1\dataHelper.py", line 62, in get_restaurant_dataset
    with open(train_dir, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SemEval14-res/train.json'
